name: Metrics Graph

on:
  schedule:
    - cron: "0 0 * * *"   # daily update
  workflow_dispatch:       # run manually
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Anjaliverma09
          template: classic
          base: header, activity, repositories
          config_timezone: Asia/Kolkata
          filename: metrics.svg
